---
name: CI

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  setup_release:
    name: Setup Release
    outputs:
      changelog_changes: ${{ steps.setup_release.outputs.changelog_changes }}
      changelog_date: ${{ steps.setup_release.outputs.changelog_date }}
      changelog_exists: ${{ steps.setup_release.outputs.changelog_exists }}
      changelog_release_exists: ${{ steps.setup_release.outputs.changelog_release_exists }}
      changelog_url: ${{ steps.setup_release.outputs.changelog_url }}
      changelog_version: ${{ steps.setup_release.outputs.changelog_version }}
      publish_pre_release: ${{ steps.setup_release.outputs.publish_pre_release }}
      publish_release: ${{ steps.setup_release.outputs.publish_release }}
      publish_stable_release: ${{ steps.setup_release.outputs.publish_stable_release }}
      release_body: ${{ steps.setup_release.outputs.release_body }}
      release_build: ${{ steps.setup_release.outputs.release_build }}
      release_commit: ${{ steps.setup_release.outputs.release_commit }}
      release_generate_release_notes: ${{ steps.setup_release.outputs.release_generate_release_notes }}
      release_tag: ${{ steps.setup_release.outputs.release_tag }}
      release_version: ${{ steps.setup_release.outputs.release_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Release
        id: setup_release
        uses: LizardByte/setup-release-action@v2023.1210.1904
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: windows-2019
    needs:
      - setup_release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Set up Python Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements-dev.txt

      - name: Build pyinstaller package
        run: |
          python -u ./scripts/build.py

      - name: Upload Artifacts
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v3
        with:
          name: GSMS
          if-no-files-found: error  # 'warn' or 'ignore' are also available, defaults to `warn`
          path: |
            ${{ github.workspace }}/dist/gsms.exe

      - name: Create/Update GitHub Release
        if: ${{ needs.setup_release.outputs.publish_release == 'true' }}
        uses: LizardByte/create-release-action@v2023.1128.2625
        with:
          allowUpdates: false
          artifacts: "${{ github.workspace }}/dist/gsms.exe"
          body: ''
          discussionCategory: announcements
          generateReleaseNotes: true
          name: ${{ needs.setup_release.outputs.release_tag }}
          prerelease: ${{ needs.setup_release.outputs.publish_pre_release }}
          tag: ${{ needs.setup_release.outputs.release_tag }}
          token: ${{ secrets.GH_BOT_TOKEN }}
